import xarray as xr
import numpy as np
import pandas as pd
import h3_utils

OUTPUT_FILE = "real_ennore_wind.sql"

def sql_ts(ts_string):
    return pd.to_datetime(ts_string).strftime("%Y-%m-%d %H:%M:%S+0000")

def generate_wind_sql():
    # Tumhari specific wind file ka naam
    nc_file = "7410704ea21710183b11f17c9bf25383.nc"
    print(f"Reading {nc_file}...")
    
    # NetCDF file load karna
    ds = xr.open_dataset(nc_file)
    
    df = ds.to_dataframe().reset_index()
    # Zameen wale coordinates hatao, sirf valid u10 aur v10 lo
    df = df.dropna(subset=['u10', 'v10'])
    
    print(f"Loaded {len(df)} valid wind readings. Generating SQL...")
    
    lines = [
        "-- real_ennore_wind.sql -- ECMWF Wind Data",
        "-- Generated by ingest_wind_demo.py",
        "",
        "-- === Wind readings (Real Data) ===",
    ]
    
    success_count = 0
    for _, row in df.iterrows():
        lat = float(row['latitude'])
        lon = float(row['longitude'])
        u10 = float(row['u10'])
        v10 = float(row['v10'])
        
        # ECMWF data mein time variable 'valid_time' hota hai
        ts_val = row.get('valid_time', row.get('time'))
        
        # Physics Calculation: Speed (m/s) and Direction (degrees)
        speed = np.hypot(u10, v10)
        direction = (90 - np.degrees(np.arctan2(v10, u10))) % 360
        
        h3idx = h3_utils.encode_point(lat, lon)
        
        # UPSERT LOGIC: Yeh sabse important part hai.
        # Agar H3 index aur timestamp par ocean current pehle se hai, toh usko UPDATE kar dega.
        # Agar nahi hai, toh ek nayi row INSERT kar dega.
        lines.append(
            "INSERT INTO ocean_readings (lat, lon, wind_speed_ms, wind_dir_deg, h3_index, ts) "
            f"VALUES (ROUND({lat}, 5), ROUND({lon}, 5), ROUND({speed}, 3), ROUND({direction}, 1), {h3idx}, "
            f"'{sql_ts(ts_val)}') "
            "ON CONFLICT (h3_index, ts) DO UPDATE SET "
            "wind_speed_ms = EXCLUDED.wind_speed_ms, "
            "wind_dir_deg = EXCLUDED.wind_dir_deg;"
        )
        success_count += 1

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")
        
    print(f"Done! Wrote {success_count} wind readings to {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_wind_sql()