"""
ingest_wind_demo.py - Parses real ECMWF/ERA5 wind NetCDF (.nc) data (7410704ea21710183b11f17c9bf25383.nc)
and generates SQL INSERT statements for PostgreSQL / TimescaleDB with H3 spatial indexing and UPSERT logic.
"""

import glob
import os
import h3_utils
import numpy as np
import pandas as pd
import xarray as xr

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(BASE_DIR, "real_ennore_wind.sql")
DEFAULT_WIND_FILE = os.path.join(BASE_DIR, "7410704ea21710183b11f17c9bf25383.nc")


def sql_ts(ts_string):
    return pd.to_datetime(ts_string).strftime("%Y-%m-%d %H:%M:%S+0000")


def find_wind_nc_file() -> str | None:
    if os.path.exists(DEFAULT_WIND_FILE):
        return DEFAULT_WIND_FILE
    nc_files = glob.glob(os.path.join(BASE_DIR, "*.nc"))
    for f in nc_files:
        try:
            with xr.open_dataset(f) as ds:
                vars_lower = [str(v).lower() for v in ds.data_vars]
                if any(w in vars_lower for w in ["u10", "v10", "wind_u", "wind_v", "si10", "eastward_wind", "northward_wind"]):
                    return f
        except Exception:
            continue
    return nc_files[0] if nc_files else None


def generate_wind_sql():
    nc_file = find_wind_nc_file()
    if not nc_file:
        print(f"ERROR: No wind .nc files found in {BASE_DIR}")
        return

    print(f"Reading wind data from {nc_file}...")
    ds = xr.open_dataset(nc_file)

    # Detect coordinate names
    lat_col = next((c for c in ds.coords if c.lower() in ["latitude", "lat", "y"]), "latitude")
    lon_col = next((c for c in ds.coords if c.lower() in ["longitude", "lon", "x"]), "longitude")

    df = ds.to_dataframe().reset_index()
    
    # Filter valid u10 and v10 readings
    u_col = "u10" if "u10" in df.columns else next((c for c in df.columns if "wind_u" in c or c == "u"), None)
    v_col = "v10" if "v10" in df.columns else next((c for c in df.columns if "wind_v" in c or c == "v"), None)

    if not u_col or not v_col:
        print(f"ERROR: Could not find u/v wind components in {nc_file}")
        return

    df = df.dropna(subset=[u_col, v_col])
    print(f"Loaded {len(df)} valid wind readings. Generating SQL...")

    lines = [
        "-- real_ennore_wind.sql -- ECMWF / ERA5 Wind Data",
        "-- Generated by ingest_wind_demo.py",
        "",
        "-- === Wind readings (Real Data) ===",
    ]

    success_count = 0
    for _, row in df.iterrows():
        lat = float(row[lat_col])
        lon = float(row[lon_col])
        u10 = float(row[u_col])
        v10 = float(row[v_col])

        # ECMWF data uses valid_time or time
        ts_val = row.get("valid_time") if "valid_time" in row else row.get("time", "2017-01-27 12:00:00")

        # Physics Calculation: Speed (m/s) and Direction (degrees)
        speed = np.hypot(u10, v10)
        direction = (90 - np.degrees(np.arctan2(v10, u10))) % 360

        h3idx = h3_utils.encode_point(lat, lon)

        # UPSERT LOGIC: Merges with existing ocean currents at the same (h3_index, ts)
        lines.append(
            "INSERT INTO ocean_readings (lat, lon, wind_speed_ms, wind_dir_deg, h3_index, ts) "
            f"VALUES (ROUND({lat}, 5), ROUND({lon}, 5), ROUND({speed}, 3), ROUND({direction}, 1), {h3idx}, "
            f"'{sql_ts(ts_val)}') "
            "ON CONFLICT (h3_index, ts) DO UPDATE SET "
            "wind_speed_ms = EXCLUDED.wind_speed_ms, "
            "wind_dir_deg = EXCLUDED.wind_dir_deg;"
        )
        success_count += 1

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Done! Wrote {success_count} wind readings to {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_wind_sql()
