"""
ingest_wind_demo.py - Parses real wind NetCDF (.nc) files (e.g., ERA5 / CMEMS 7410704ea21710183b11f17c9bf25383.nc)
and generates SQL INSERT statements for PostgreSQL / TimescaleDB with H3 spatial indexing.
"""

import glob
import os
import h3_utils
import numpy as np
import pandas as pd
import xarray as xr

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(BASE_DIR, "real_ennore_wind.sql")
DEFAULT_WIND_FILE = os.path.join(BASE_DIR, "7410704ea21710183b11f17c9bf25383.nc")


def sql_ts(ts_val):
    return pd.to_datetime(ts_val).strftime("%Y-%m-%d %H:%M:%S+0000")


def find_wind_nc_file() -> str | None:
    # First check default expected file
    if os.path.exists(DEFAULT_WIND_FILE):
        return DEFAULT_WIND_FILE
    
    # Search all .nc files in directory
    nc_files = glob.glob(os.path.join(BASE_DIR, "*.nc"))
    for f in nc_files:
        try:
            with xr.open_dataset(f) as ds:
                vars_lower = [str(v).lower() for v in ds.data_vars]
                if any(w in vars_lower for w in ["u10", "v10", "wind_u", "wind_v", "si10", "eastward_wind", "northward_wind", "u", "v"]):
                    return f
        except Exception:
            continue
    return nc_files[0] if nc_files else None


def generate_wind_sql():
    nc_file = find_wind_nc_file()
    if not nc_file:
        print(f"ERROR: No wind .nc files found in {BASE_DIR}")
        return

    print(f"Reading wind data from {nc_file}...")
    ds = xr.open_dataset(nc_file)

    # Detect coordinate names
    lat_col = next((c for c in ds.coords if c.lower() in ["latitude", "lat", "y"]), None)
    lon_col = next((c for c in ds.coords if c.lower() in ["longitude", "lon", "x"]), None)
    time_col = next((c for c in ds.coords if c.lower() in ["time", "valid_time", "time_counter"]), None)

    if not lat_col or not lon_col:
        print(f"ERROR: Could not detect lat/lon coordinates in {nc_file}")
        return

    # Detect wind speed / component variables
    vars_map = {str(k).lower(): k for k in ds.data_vars}
    u_var = vars_map.get("u10") or vars_map.get("wind_u") or vars_map.get("eastward_wind") or vars_map.get("u")
    v_var = vars_map.get("v10") or vars_map.get("wind_v") or vars_map.get("northward_wind") or vars_map.get("v")
    speed_var = vars_map.get("si10") or vars_map.get("wind_speed") or vars_map.get("speed")
    dir_var = vars_map.get("wind_dir") or vars_map.get("wdir10") or vars_map.get("direction")

    # If depth / expver exists, slice first level
    if "depth" in ds.dims:
        ds = ds.isel(depth=0)
    if "expver" in ds.dims:
        ds = ds.isel(expver=0)

    df = ds.to_dataframe().reset_index()

    # Drop NaNs
    active_vars = [v for v in [u_var, v_var, speed_var, dir_var] if v]
    if active_vars:
        df = df.dropna(subset=[active_vars[0]])

    print(f"Loaded {len(df)} valid wind readings. Generating SQL...")

    lines = [
        "-- real_ennore_wind.sql -- Ennore 2017 Wind Measurements",
        "-- Generated by ingest_wind_demo.py",
        "",
        "-- === Wind readings (Real Data) ===",
    ]

    success_count = 0
    for _, row in df.iterrows():
        lat = float(row[lat_col])
        lon = float(row[lon_col])
        ts_val = row[time_col] if time_col and time_col in row else "2017-01-27 12:00:00"

        if u_var and v_var:
            u_val = float(row[u_var])
            v_val = float(row[v_var])
            speed = float(np.hypot(u_val, v_val))
            # Direction towards which wind is blowing (oceanographic standard for drift modeling)
            direction = float((90 - np.degrees(np.arctan2(v_val, u_val))) % 360)
        elif speed_var and dir_var:
            speed = float(row[speed_var])
            direction = float(row[dir_var])
        elif speed_var:
            speed = float(row[speed_var])
            direction = 0.0
        else:
            continue

        h3idx = h3_utils.encode_point(lat, lon)

        lines.append(
            "INSERT INTO ocean_readings (lat, lon, wind_speed_ms, wind_dir_deg, h3_index, ts) "
            f"VALUES ({round(lat, 5)}, {round(lon, 5)}, {round(speed, 3)}, {round(direction, 1)}, {h3idx}, "
            f"'{sql_ts(ts_val)}') ON CONFLICT (h3_index, ts) DO UPDATE SET "
            f"wind_speed_ms = EXCLUDED.wind_speed_ms, wind_dir_deg = EXCLUDED.wind_dir_deg;"
        )
        success_count += 1

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Done! Wrote {success_count} wind readings to {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_wind_sql()
