import glob
import os
import h3_utils
import numpy as np
import pandas as pd
import xarray as xr

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(BASE_DIR, "real_ennore_ocean.sql")

def sql_ts(ts_string):
    return pd.to_datetime(ts_string).strftime("%Y-%m-%d %H:%M:%S+0000")

DEFAULT_OCEAN_FILE = os.path.join(BASE_DIR, "cmems_mod_glo_phy_my_0.083deg_P1D-m_1787602924183.nc")


def find_ocean_nc_file() -> str | None:
    if os.path.exists(DEFAULT_OCEAN_FILE):
        return DEFAULT_OCEAN_FILE
    nc_files = glob.glob(os.path.join(BASE_DIR, "*.nc"))
    for f in nc_files:
        try:
            with xr.open_dataset(f) as ds:
                if "uo" in ds.data_vars and "vo" in ds.data_vars:
                    return f
        except Exception:
            continue
    return nc_files[0] if nc_files else None


def generate_ocean_sql():
    nc_file = find_ocean_nc_file()
    if not nc_file:
        print(f"ERROR: No ocean current .nc files found in {BASE_DIR}")
        return
    print(f"Reading ocean current data from {nc_file}...")
    
    # NetCDF file load karna
    ds = xr.open_dataset(nc_file)
    
    # Samundar ki satah (surface) ka data lena (depth=0)
    if 'depth' in ds.dims:
        ds = ds.isel(depth=0)
        
    df = ds.to_dataframe().reset_index()
    # Zameen (land) wale coordinates hata do kyu ki wahan ocean currents nahi hote
    df = df.dropna(subset=['uo', 'vo'])
    
    print(f"Loaded {len(df)} valid ocean current readings. Generating SQL...")
    
    lines = [
        "-- real_ennore_ocean.sql -- Ennore 2017 Ocean Currents",
        "-- Generated by ingest_ocean_demo.py",
        "",
        "-- === Ocean readings (Real Data) ===",
    ]
    
    success_count = 0
    for _, row in df.iterrows():
        lat = float(row['latitude'])
        lon = float(row['longitude'])
        uo = float(row['uo'])
        vo = float(row['vo'])
        ts_val = row['time']
        
        # Calculate Speed (m/s) and Direction (degrees) from uo and vo
        speed = np.hypot(uo, vo)
        direction = (90 - np.degrees(np.arctan2(vo, uo))) % 360
        
        h3idx = h3_utils.encode_point(lat, lon)
        
        lines.append(
            "INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) "
            f"VALUES ({round(lat, 5)}, {round(lon, 5)}, {round(speed, 3)}, {round(direction, 1)}, {h3idx}, "
            f"'{sql_ts(ts_val)}') ON CONFLICT (h3_index, ts) DO UPDATE SET "
            f"current_speed_ms = EXCLUDED.current_speed_ms, current_dir_deg = EXCLUDED.current_dir_deg;"
        )
        success_count += 1

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")
        
    print(f"Done! Wrote {success_count} ocean readings to {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_ocean_sql()