import os
from datetime import datetime
import pandas as pd
import h3_utils

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# File Names
CSV_FILE = os.path.join(BASE_DIR, "ennore_ais_2017_massive.csv")
OUTPUT_FILE = os.path.join(BASE_DIR, "real_ennore_data.sql")

# ==========================================
# ⚠️ APNI CSV KE HISAAB SE COLUMN NAMES SET KARO
# ==========================================
COL_MMSI = 'MMSI'
COL_LAT = 'Latitude'
COL_LON = 'Longitude'
COL_SPEED = 'Speed_Knots'       # Agar CSV mein speed_kn hai toh wo likho
COL_HEADING = 'Heading'   # Agar CSV mein heading_deg hai toh wo likho
COL_TS = 'Timestamp'      # Ya 'time', 'date', jo bhi CSV mein likha ho
# ==========================================

def sql_ts(ts_string):
    # Pandas reads it as a string or datetime, we ensure it's a string format for SQL
    try:
        dt = pd.to_datetime(ts_string)
        return dt.strftime("%Y-%m-%d %H:%M:%S+0000")
    except:
        return ts_string

def generate_sql_from_csv():
    print(f"Reading {CSV_FILE} (This might take a few seconds if it's massive)...")
    try:
        df = pd.read_csv(CSV_FILE)
    except FileNotFoundError:
        print(f"ERROR: {CSV_FILE} file nahi mili! Usse isi folder mein copy karo.")
        return

    print(f"Successfully loaded {len(df)} rows. Generating SQL...")
    
    lines = [
        "-- real_ennore_data.sql -- Ennore 2017 Historical AIS Data",
        "-- Generated by ingest_real_demo.py",
        "",
        "-- Hum purana synthetic data delete nahi kar rahe, uske upar hi add kar rahe hain",
        "-- Taki dono datasets ek hi DB mein majood rahein.",
        "",
        "-- === AIS pings (Real Data) ===",
    ]
    
    success_count = 0
    for index, row in df.iterrows():
        try:
            mmsi = int(row[COL_MMSI])
            lat = float(row[COL_LAT])
            lon = float(row[COL_LON])
            speed = float(row[COL_SPEED]) if pd.notna(row[COL_SPEED]) else 0.0
            heading = float(row[COL_HEADING]) if pd.notna(row[COL_HEADING]) else 0.0
            ts_val = row[COL_TS]
            
            # H3 Hexagon calculate kar rahe hain
            h3idx = h3_utils.encode_point(lat, lon)
            
            lines.append(
                "INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) "
                f"VALUES ({mmsi}, {lat}, {lon}, {speed}, {heading}, {h3idx}, "
                f"'{sql_ts(ts_val)}') ON CONFLICT (mmsi, ts) DO NOTHING;"
            )
            success_count += 1
        except Exception as e:
            # Agar kisi row mein data kharab hua toh skip kar denge
            continue

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Done! Wrote {success_count} real AIS pings to {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_sql_from_csv()