-- sample_data.sql -- fixed demo dataset for SAMUDRA-NETRA Layer 2
-- Generated by generate_sample_data.py with random.seed(42) -- rerunning
-- the script reproduces this exact file, so it's safe to regenerate.
-- Apply AFTER schema.sql:
--   docker exec -i samudra_timescaledb psql -U samudra -d samudra_netra < sample_data.sql

TRUNCATE spill_hex_coverage, spill_detections, ais_pings, ocean_readings;

-- === AIS pings ===
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636731262, 21.53613, 69.37678, 14.4, 250.6, 613665313805828095, '2026-08-20 00:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636731262, 21.53634, 69.37144, 15.7, 120.8, 613665313843576831, '2026-08-20 00:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636731262, 21.5217, 69.36258, 14.8, 216.7, 613665314164441087, '2026-08-20 01:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636731262, 21.57877, 69.41246, 12.3, 349.3, 613665314508374015, '2026-08-20 01:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636731262, 21.54156, 69.40302, 14.6, 222.0, 613665313862451199, '2026-08-20 02:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636731262, 21.61539, 69.41338, 13.6, 16.5, 613665314558705663, '2026-08-20 02:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419688508, 21.53837, 69.28682, 8.8, 99.8, 613665320934047743, '2026-08-20 00:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419688508, 21.54744, 69.28776, 11.0, 75.2, 613665314686631935, '2026-08-20 00:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419688508, 21.53439, 69.32302, 13.2, 218.7, 613665314613231615, '2026-08-20 01:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419688508, 21.52377, 69.32244, 9.3, 136.2, 613665314650980351, '2026-08-20 01:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419688508, 21.61711, 69.32362, 12.5, 245.8, 613665318281150463, '2026-08-20 02:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419688508, 21.6148, 69.35322, 9.8, 11.5, 613665319484915711, '2026-08-20 02:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351850800, 21.56464, 69.28032, 15.0, 113.0, 613665318543294463, '2026-08-20 00:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351850800, 21.5743, 69.28219, 15.3, 164.7, 613665318505545727, '2026-08-20 00:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351850800, 21.56053, 69.27512, 12.5, 94.3, 613665318532808703, '2026-08-20 01:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351850800, 21.58725, 69.33113, 11.2, 78.7, 613665314351087615, '2026-08-20 01:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351850800, 21.64434, 69.30147, 8.7, 16.9, 613665318320996351, '2026-08-20 02:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351850800, 21.53108, 69.32444, 14.3, 151.6, 613665314613231615, '2026-08-20 02:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636539898, 21.48906, 69.31449, 15.8, 309.0, 613665320399273983, '2026-08-20 00:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636539898, 21.4794, 69.32611, 13.5, 192.8, 613665320430731263, '2026-08-20 00:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636539898, 21.48507, 69.33294, 8.9, 156.1, 613665314174926847, '2026-08-20 01:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636539898, 21.49989, 69.37033, 15.0, 94.6, 613665314072166399, '2026-08-20 01:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636539898, 21.50913, 69.29592, 15.3, 312.5, 613665320462188543, '2026-08-20 02:00:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636539898, 21.48383, 69.36033, 12.9, 54.9, 613665314114109439, '2026-08-20 02:30:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351665579, 23.3605, 71.22852, 12.0, 175.4, 613663934777393151, '2026-08-17 11:52:06+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419480612, 23.13617, 70.91083, 1.2, 315.2, 613663953878253567, '2026-08-19 07:51:32+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419189814, 22.69572, 70.85608, 10.7, 45.1, 613663837710712831, '2026-08-17 07:35:06+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563676510, 20.99538, 69.84686, 19.3, 333.5, 613665035081744383, '2026-08-18 10:19:30+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351847581, 21.43515, 71.48302, 8.8, 185.8, 613665798602358783, '2026-08-18 07:12:31+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419359947, 21.17409, 69.1833, 4.6, 79.1, 613665271711793151, '2026-08-18 11:38:30+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419842225, 22.39331, 68.8013, 17.2, 25.4, 613664280966856703, '2026-08-17 12:48:35+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351392004, 22.50693, 68.74983, 18.7, 205.0, 613667222065250303, '2026-08-19 20:28:24+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563354801, 22.85386, 70.82624, 1.9, 154.7, 613663950527004671, '2026-08-19 16:17:25+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563531071, 21.90107, 70.55177, 19.7, 35.3, 613664011830951935, '2026-08-18 05:31:03+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563863587, 21.51791, 71.01585, 3.8, 161.1, 613665792080216063, '2026-08-19 12:05:48+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563292401, 21.33564, 68.87432, 8.9, 309.2, 613665308267249663, '2026-08-17 11:31:29+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636202664, 20.65176, 71.49749, 19.4, 332.6, 613665780315193343, '2026-08-17 17:48:21+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351274389, 21.71924, 69.68475, 18.0, 59.1, 613664021691760639, '2026-08-17 15:44:42+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419509386, 21.29561, 70.74425, 8.5, 343.7, 613663994359578623, '2026-08-18 21:14:21+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636794022, 22.65522, 68.54179, 19.4, 207.9, 613667210314907647, '2026-08-19 08:38:13+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636163918, 22.74393, 68.20008, 10.1, 306.1, 613667195546763263, '2026-08-18 11:56:21+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351159642, 23.38234, 68.28039, 11.9, 242.4, 613666182934822911, '2026-08-19 16:37:14+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351523389, 20.85966, 71.11601, 11.9, 222.4, 613665771026907135, '2026-08-19 12:16:20+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563789305, 22.25102, 69.82974, 4.1, 257.1, 613664250050641919, '2026-08-17 10:42:04+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351378517, 21.68736, 70.35092, 6.3, 269.9, 613663966593286143, '2026-08-19 08:24:00+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419109767, 21.87486, 71.49459, 1.5, 76.5, 613664060277260287, '2026-08-17 06:16:51+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (538238890, 23.29978, 71.08302, 7.4, 56.6, 613663933691068415, '2026-08-17 14:41:33+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636837715, 21.40755, 71.44349, 10.6, 239.8, 613665798933708799, '2026-08-17 19:53:19+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636413921, 23.29527, 68.36255, 5.3, 319.4, 613666196759248895, '2026-08-17 14:46:29+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636262998, 21.31704, 70.1169, 4.1, 227.7, 613663982605041663, '2026-08-18 02:19:54+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (538629959, 21.9656, 71.16868, 1.8, 152.1, 613664057139920895, '2026-08-17 17:04:49+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (538146228, 20.51064, 70.69892, 5.2, 266.1, 613665928831303679, '2026-08-18 08:07:40+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636839945, 21.78306, 68.03384, 17.7, 324.5, 613667337536536575, '2026-08-20 00:34:56+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636137778, 23.00379, 70.03878, 2.5, 110.7, 613663862798942207, '2026-08-19 19:20:14+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419475190, 21.13023, 68.87335, 15.6, 317.4, 613665326225162239, '2026-08-19 22:35:55+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563750810, 22.74843, 71.24017, 3.3, 287.2, 613663913831038975, '2026-08-19 12:57:17+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351532322, 20.57436, 70.57798, 18.6, 288.0, 613665007055405055, '2026-08-19 06:04:57+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351379766, 20.97759, 70.45447, 0.8, 169.0, 613665042723766271, '2026-08-19 02:27:25+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351956253, 23.25536, 69.2238, 17.4, 80.0, 613664107110858751, '2026-08-17 18:55:16+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351517821, 21.48479, 71.02524, 5.6, 230.3, 613665788135473151, '2026-08-17 08:23:02+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563812526, 23.44345, 69.87676, 2.3, 348.4, 613664225027424255, '2026-08-17 10:22:29+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351708792, 23.3876, 68.92913, 8.7, 261.5, 613664139742543871, '2026-08-19 22:11:42+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (538557592, 22.31863, 69.78998, 11.5, 91.4, 613664250298105855, '2026-08-19 02:15:57+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563101773, 22.05976, 70.82279, 18.8, 264.6, 613664085453570047, '2026-08-18 04:32:46+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351481913, 21.79389, 71.32106, 12.5, 238.2, 613664052580712447, '2026-08-17 11:42:16+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419854717, 23.20014, 69.77493, 6.5, 250.3, 613664111642804223, '2026-08-18 05:59:01+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636233470, 21.07552, 70.32725, 15.0, 62.5, 613665039471083519, '2026-08-19 02:42:05+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636415568, 21.71823, 70.91804, 4.2, 282.1, 613664058098319359, '2026-08-19 08:07:15+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636786508, 21.46675, 69.54625, 10.2, 285.0, 613665317083676671, '2026-08-18 05:21:17+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351790855, 20.75439, 69.80408, 6.7, 293.8, 613665052938993663, '2026-08-18 08:25:41+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351805477, 21.43126, 70.82297, 0.9, 353.2, 613665793445462015, '2026-08-19 19:23:25+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636991014, 22.80547, 69.59396, 11.5, 257.9, 613664131234398207, '2026-08-17 14:11:53+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563618392, 21.69896, 68.5165, 17.9, 308.9, 613667347510591487, '2026-08-18 04:29:28+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (419916232, 21.77544, 68.6156, 10.4, 18.0, 613667341860863999, '2026-08-17 09:01:35+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351989545, 20.86408, 68.46669, 10.6, 200.7, 613665215881412607, '2026-08-18 20:32:44+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (538891937, 23.17428, 70.14428, 10.1, 298.2, 613664191261179903, '2026-08-18 02:12:44+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (636567574, 23.19162, 70.60279, 5.2, 88.8, 613664199301660671, '2026-08-18 19:49:24+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (538903013, 22.83302, 69.69609, 8.8, 256.2, 613664132205379583, '2026-08-19 12:46:27+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351384913, 21.50754, 71.12559, 3.0, 137.5, 613665787535687679, '2026-08-20 00:11:54+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (351840734, 21.14186, 69.45204, 9.3, 22.4, 613665274230472703, '2026-08-19 06:10:35+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563508396, 23.21452, 70.04428, 17.1, 274.8, 613664195015081983, '2026-08-18 03:55:20+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563600149, 20.51769, 69.23116, 17.1, 342.3, 613664976669769727, '2026-08-17 23:44:59+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563664365, 22.74255, 69.91146, 4.4, 78.8, 613663884785483775, '2026-08-18 10:33:56+0000') ON CONFLICT (mmsi, ts) DO NOTHING;
INSERT INTO ais_pings (mmsi, lat, lon, speed_kn, heading_deg, h3_index, ts) VALUES (563609232, 20.58707, 69.17645, 8.1, 59.3, 613664974874607615, '2026-08-18 05:06:06+0000') ON CONFLICT (mmsi, ts) DO NOTHING;

-- === Ocean readings ===
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.90217, 68.4467, 0.06, 141.5, 613667377963335679, '2026-08-18 09:11:50+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.19318, 68.09486, 0.3, 165.7, 613667214358216703, '2026-08-18 07:43:19+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.65085, 69.32686, 0.72, 273.3, 613664975883337727, '2026-08-19 14:45:37+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.63738, 70.63203, 0.55, 29.4, 613663976540078079, '2026-08-17 18:06:05+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.55815, 69.88797, 0.77, 233.4, 613665050843938815, '2026-08-17 06:00:23+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.8437, 70.28114, 2.09, 71.6, 613663833667403775, '2026-08-17 23:41:42+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.56114, 68.53334, 1.47, 202.5, 613665233784799231, '2026-08-19 20:54:43+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.15389, 70.44813, 0.37, 218.0, 613665040611934207, '2026-08-17 22:47:00+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.74378, 68.40087, 2.12, 38.8, 613667196110897151, '2026-08-17 19:00:37+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.57704, 69.09185, 2.11, 142.4, 613664962738388991, '2026-08-18 05:13:51+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.64504, 68.26599, 1.38, 36.6, 613667195504820223, '2026-08-18 04:16:32+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.81744, 70.97603, 0.27, 353.2, 613663918792900607, '2026-08-18 10:46:13+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.84791, 69.21521, 0.82, 181.6, 613664119953817599, '2026-08-18 23:09:24+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.52369, 70.97351, 0.23, 344.9, 613665792090701823, '2026-08-17 18:47:31+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.40676, 70.90048, 0.96, 263.4, 613664075401920511, '2026-08-18 03:04:25+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (23.39642, 68.94529, 1.18, 173.6, 613664139757223935, '2026-08-17 19:48:34+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.80672, 70.55859, 1.87, 298.2, 613663978094067711, '2026-08-19 10:40:31+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.75999, 71.08571, 1.02, 219.1, 613665769479208959, '2026-08-19 12:26:30+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.63697, 68.10045, 0.4, 76.2, 613667338922754047, '2026-08-17 16:43:53+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.8935, 69.19119, 1.54, 99.2, 613664121746882559, '2026-08-17 14:37:01+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.53045, 71.31822, 1.58, 175.4, 613665932369199103, '2026-08-19 23:50:09+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.77449, 70.41713, 1.08, 284.7, 613663873148387327, '2026-08-18 07:29:41+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.77916, 68.77559, 0.67, 208.8, 613665214497292287, '2026-08-18 04:11:28+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.91978, 69.85823, 1.64, 118.8, 613664006709706751, '2026-08-18 23:21:49+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.60856, 68.94821, 0.27, 69.1, 613664279897309183, '2026-08-19 11:53:56+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.85866, 69.87552, 0.41, 77.7, 613665033125101567, '2026-08-17 23:07:20+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.9526, 70.53605, 1.15, 101.6, 613664011445075967, '2026-08-17 07:41:03+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.80158, 68.67941, 0.39, 5.1, 613665210969882623, '2026-08-19 13:37:16+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.10241, 68.96009, 1.22, 250.4, 613664295563034623, '2026-08-17 07:51:02+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.87884, 71.03961, 1.92, 206.1, 613665774709506047, '2026-08-18 18:39:24+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.90819, 69.54164, 0.11, 337.8, 613664265919791103, '2026-08-19 16:43:32+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.93319, 70.8774, 0.16, 226.0, 613664087796088831, '2026-08-19 01:08:56+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.66083, 68.52219, 0.67, 356.8, 613665234030166015, '2026-08-18 13:28:31+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.85535, 70.67555, 1.74, 81.0, 613665010419236863, '2026-08-18 10:20:42+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (22.06772, 69.5768, 1.89, 355.4, 613664271923937279, '2026-08-18 22:07:26+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.41614, 70.1736, 1.63, 340.2, 613663984083533823, '2026-08-18 10:06:23+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.12336, 68.73859, 0.35, 62.4, 613665323240914943, '2026-08-18 06:26:57+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (20.72519, 68.00937, 1.31, 104.6, 613665255175749631, '2026-08-18 21:33:49+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (21.19443, 70.47435, 1.0, 246.8, 613663993436831743, '2026-08-18 03:23:05+0000') ON CONFLICT (h3_index, ts) DO NOTHING;
INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) VALUES (23.27173, 70.7574, 1.45, 335.2, 613664200333459455, '2026-08-18 08:59:44+0000') ON CONFLICT (h3_index, ts) DO NOTHING;

-- === Spills (with hex coverage) ===

WITH new_spill AS (
    INSERT INTO spill_detections (confidence, area_km2, centroid_lat, centroid_lon, ts)
    VALUES (0.91, 4.7, 21.614000000444474, 69.35750000142471, '2026-08-20 03:00:00+0000')
    RETURNING spill_id
)
INSERT INTO spill_hex_coverage (spill_id, h3_index, ts)
SELECT spill_id, unnest(ARRAY[613665314407710719,613665319491207167,613665314548219903,613665314422390783,613665319476527103,613665314363670527,613665314348990463,613665319543635967,613665314430779391,613665319549927423,613665314416099327,613665314541928447,613665319499595775,613665319438778367,613665319484915711,613665314357379071,613665314355281919,613665319552024575,613665314424487935,613665318291636223,613665314550317055,613665319493304319,613665319482818559,613665319478624255,613665314365767679,613665319497498623,613665318287441919,613665314539831295,613665319686242303,613665319545733119,613665314432876543,613665314428682239,613665314544025599,613665314569191423,613665319541538815,613665319501692927,613665314583871487,613665319472332799,613665318253887487,613665314359476223,613665314485305343,613665314346893311,613665319445069823,613665319442972671,613665314361573375,613665318283247615,613665314581774335,613665319474429951,613665319539441663,613665314426585087,613665319489110015,613665314552414207,613665314411905023,613665319495401471,613665319480721407,613665314546122751,613665314367864831,613665319451361279,613665319547830271,613665314434973695]::bigint[]), '2026-08-20 03:00:00+0000'
FROM new_spill;


WITH new_spill AS (
    INSERT INTO spill_detections (confidence, area_km2, centroid_lat, centroid_lon, ts)
    VALUES (0.63, 0.42, 22.418280001338978, 68.08754000406633, '2026-08-15 06:00:00+0000')
    RETURNING spill_id
)
INSERT INTO spill_hex_coverage (spill_id, h3_index, ts)
SELECT spill_id, unnest(ARRAY[613667217847877631,613667217849974783,613667217852071935,613667217854169087,613667212741312511,613667217868849151,613667212919570431,613667212923764735,613667212927959039]::bigint[]), '2026-08-15 06:00:00+0000'
FROM new_spill;


WITH new_spill AS (
    INSERT INTO spill_detections (confidence, area_km2, centroid_lat, centroid_lon, ts)
    VALUES (0.61, 0.56, 22.72199999981064, 69.9087799994216, '2026-08-18 06:00:00+0000')
    RETURNING spill_id
)
INSERT INTO spill_hex_coverage (spill_id, h3_index, ts)
SELECT spill_id, unnest(ARRAY[613663884831621119,613663885139902463,613663884896632831,613663884829523967,613663884827426815,613663884892438527,613663884848398335,613663884789678079,613663880972861439,613663884825329663,613663884823232511,613663884888244223,613663884821135359,613663884819038207,613663885148291071,613663884791775231,613663885081182207]::bigint[]), '2026-08-18 06:00:00+0000'
FROM new_spill;

