import xarray as xr
import numpy as np
import pandas as pd
import glob
import h3_utils

OUTPUT_FILE = "real_ennore_ocean.sql"

def sql_ts(ts_string):
    return pd.to_datetime(ts_string).strftime("%Y-%m-%d %H:%M:%S+0000")

def generate_ocean_sql():
    # Folder ki pehli .nc file automatically utha lega
    nc_file = glob.glob("*.nc")[0]
    print(f"Reading {nc_file}...")
    
    # NetCDF file load karna
    ds = xr.open_dataset(nc_file)
    
    # Samundar ki satah (surface) ka data lena (depth=0)
    if 'depth' in ds.dims:
        ds = ds.isel(depth=0)
        
    df = ds.to_dataframe().reset_index()
    # Zameen (land) wale coordinates hata do kyu ki wahan ocean currents nahi hote
    df = df.dropna(subset=['uo', 'vo'])
    
    print(f"Loaded {len(df)} valid ocean current readings. Generating SQL...")
    
    lines = [
        "-- real_ennore_ocean.sql -- Ennore 2017 Ocean Currents",
        "-- Generated by ingest_ocean_demo.py",
        "",
        "-- === Ocean readings (Real Data) ===",
    ]
    
    success_count = 0
    for _, row in df.iterrows():
        lat = float(row['latitude'])
        lon = float(row['longitude'])
        uo = float(row['uo'])
        vo = float(row['vo'])
        ts_val = row['time']
        
        # Calculate Speed (m/s) and Direction (degrees) from uo and vo
        speed = np.hypot(uo, vo)
        direction = (90 - np.degrees(np.arctan2(vo, uo))) % 360
        
        h3idx = h3_utils.encode_point(lat, lon)
        
        lines.append(
            "INSERT INTO ocean_readings (lat, lon, current_speed_ms, current_dir_deg, h3_index, ts) "
            f"VALUES (ROUND({lat}, 5), ROUND({lon}, 5), ROUND({speed}, 3), ROUND({direction}, 1), {h3idx}, "
            f"'{sql_ts(ts_val)}') ON CONFLICT (h3_index, ts) DO NOTHING;"
        )
        success_count += 1

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")
        
    print(f"Done! Wrote {success_count} ocean readings to {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_ocean_sql()